### ISSUE TITLE
Loop File Handling Logic

### ISSUE THREAD

**Issue by blevien** [Callihan-ops/arduno-flight-computer#2]
https://github.com/Callihan-ops/arduno-flight-computer/blob/6270cd2ba8a8a6877aa0328e9d3be6c5f90b5851/main.ino#L50-L63

In this block, you close your file on your first read if the button isn't pressed (since it's pulled high), and never re-open it for writing... 

You should only open itfor writing ONCE when the state is changed to "Logging", and only close it once when the state is changed to "Not Logging". We also need to make sure after you open it, you go to the end and start writing at the end.

I haven't tested because I don't have the hardware, but try something like:

```
void loop() {

  int sensorVal = digitalRead(2);
  
  if (sensorVal == LOW) 
  {
    logging = !logging;  // Flip state of "logging" when button is pressed

     if(logging)
     {
      writeFile = SD.open("example.txt", FILE_WRITE);
      writeFile.seek(EOF);
      }
   else
    {
    writeFile.close();
    }
}

  if(logging)
  {
    Serial.print("Logging...\n"); 
    writeFile.println(genTxt(5));
  }
  delay(500);
}

```

**Comment by marloweoliver** [comment]
This is far more efficient then what I have currently. This method will probably be added

**Comment by marloweoliver** [comment]
The only issue with that is this error message.
`exit status`
`expected initializer before 'logging'`
